### PR TITLE
Add Initial Folder Structure for Data Commons Client

### PR DESCRIPTION
**Pull request by jm-rivera**
This is a housekeeping PR which adds the folder structure we plan to implement, based on the design document.
The folders are empty (other than `__init__` files).

We decided to put everything inside `/datacommons_client` while the DC team decides how they want to structure things with the different packages and libraries. The structure could always be refactored in the future, but this will allow us to develop in a relatively clean environment without deleting or moving things around.

### CODE REVIEW

**Review by beets — APPROVED** [review]
Thanks for the initial pull request! I've updated the cloud build tests to stream output back to github, and added you both as collaborators so you shouldn't need /gcbrun to trigger tests in the future.

**Review by dwnoble — APPROVED** [review]
Thanks Jorge!

**Comment by beets** [comment]
@jm-rivera you should be able to merge after addressing the CLA check (from google-cla above). please let us know if you run into any issues with that

**Comment by jm-rivera** [comment]
> @jm-rivera you should be able to merge after addressing the CLA check (from google-cla above). please let us know if you run into any issues with that

Thank you @beets! Our legal department signed the docusign on Friday and now it says it is waiting for approval on your side. Would you mind checking if there's something else we should do for that to come through?

**Review by gmechali — APPROVED** [review]

**Comment by jm-rivera** [comment]
> > @jm-rivera you should be able to merge after addressing the CLA check (from google-cla above). please let us know if you run into any issues with that

Hi @beets - we're finally covered by the CLA! So the checks are finally passing.
What will be the process once different reviewers approve?  I don't have rights to push to the master branch (so right now merging is blocked for me)

**Comment by beets** [comment]
hi @jm-rivera - your team should have access to merge -- could you please give it a try! So glad you're unblocked!

**Pull request merged**
